/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyDouble;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.matches;
import static org.mockito.Mockito.atLeast;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

@ExtendWith(MockitoExtension.class)
public class AppTest {

    @Mock Connection conn;
    @Mock PreparedStatement createUsersStmt;
    @Mock PreparedStatement createProductsStmt;
    @Mock PreparedStatement createSessionsStmt;
    @Mock PreparedStatement createPageviewsStmt;
    @Mock PreparedStatement createOrdersStmt;
    @Mock PreparedStatement createOrderItemsStmt;
    @Mock PreparedStatement createOrderItemRefundsStmt;
    
    @Test void appCreateTables() {
        try{
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?users *\\( *"+
                " *user_id +INT +AUTO_INCREMENT +PRIMARY +KEY *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS users ("+
                "  user_id INT AUTO_INCREMENT PRIMARY KEY"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?products *\\( *"+
                " *product_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *product_name +VARCHAR\\(50\\) *, *"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS products ("+
                "  product_id INT AUTO_INCREMENT PRIMARY KEY,"+
                "  product_name VARCHAR(50), "+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?website_sessions *\\( *"+
                " *website_session_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *user_id +INT +REFERENCES +users\\(user_id\\) *, *"+
                " *is_repeat_session +INT *, *"+
                " *utm_source +VARCHAR\\(50\\) *, *"+
                " *utm_campaign +VARCHAR\\(50\\) *, *"+
                " *utm_content +VARCHAR\\(50\\) *, *"+
                " *device_type +VARCHAR\\(50\\) *, *"+
                " *http_referer +VARCHAR\\(50\\) *, *"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS website_sessions ("+
                "  website_session_id INT AUTO_INCREMENT PRIMARY KEY, "+
                "  user_id INT REFERENCES users(user_id), "+
                "  is_repeat_session INT, "+
                "  utm_source VARCHAR(50), "+
                "  utm_campaign VARCHAR(50), "+
                "  utm_content VARCHAR(50), "+
                "  device_type VARCHAR(50), "+
                "  http_referer VARCHAR(50), "+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?website_pageviews *\\( *"+
                " *website_pageview_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *website_session_id +INT +REFERENCES +website_sessions *\\( *website_session_id *\\) *, *"+
                " *pageview_url +VARCHAR\\(50\\),"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS website_pageviews ("+
                "  website_pageview_id INT AUTO_INCREMENT PRIMARY KEY,"+
                "  website_session_id INT REFERENCES website_sessions(website_session_id),"+
                "  pageview_url VARCHAR(50),"+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?orders *\\( *"+
                " *order_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *website_session_id +INT +REFERENCES +website_sessions *\\( *website_session_id *\\) *, *"+
                " *user_id +INT +REFERENCES +users *\\( *user_id *\\) *, *"+
                " *primary_product_id +INT +REFERENCES +products *\\( *product_id *\\) *, *"+
                " *items_purchased +INT *, *"+
                " *price_usd +DOUBLE *, *"+
                " *cogs_usd +DOUBLE *, *"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS orders ("+
                "  order_id INT AUTO_INCREMENT PRIMARY KEY,"+
                "  website_session_id INT REFERENCES website_sessions(website_session_id), "+
                "  user_id INT REFERENCES users(user_id), "+
                "  primary_product_id INT REFERENCES products(product_id), "+
                "  items_purchased INT, "+
                "  price_usd DOUBLE, "+
                "  cogs_usd DOUBLE, "+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?order_items *\\( *"+
                " *order_item_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *order_id +INT +REFERENCES +orders *\\( *order_id *\\) *, *"+
                " *product_id +INT +REFERENCES +products *\\( *product_id *\\) *, *"+
                " *is_primary_item +INT *, *"+
                " *price_usd +DOUBLE *, *"+
                " *cogs_usd +DOUBLE *, *"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS order_items ("+
                "  order_item_id INT AUTO_INCREMENT PRIMARY KEY,"+
                "  order_id INT REFERENCES orders(order_id), "+
                "  product_id INT REFERENCES products(product_id),"+
                "  is_primary_item INT,"+
                "  price_usd DOUBLE,"+
                "  cogs_usd DOUBLE,"+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            when(conn.prepareStatement(matches(
                " *CREATE +(OR +REPLACE +)?TABLE +(IF +NOT +EXISTS +)?order_item_refunds *\\( *"+
                " *order_item_refund_id +INT +AUTO_INCREMENT +PRIMARY +KEY *, *"+
                " *order_item_id +INT +REFERENCES +order_items *\\( *order_item_id *\\) *, *"+
                " *order_id +INT +REFERENCES +orders *\\( *order_id *\\) *, *"+
                " *refund_amount_usd +DOUBLE *, *"+
                " *created_at +TIMESTAMP *"+
                " *\\) *;? *"
            ))).thenReturn(createUsersStmt);
            assertTrue(conn.prepareStatement("CREATE TABLE IF NOT EXISTS order_item_refunds ("+
                "  order_item_refund_id INT AUTO_INCREMENT PRIMARY KEY, "+
                "  order_item_id INT REFERENCES order_items(order_item_id), "+
                "  order_id INT REFERENCES orders(order_id), "+
                "  refund_amount_usd DOUBLE, "+
                "  created_at TIMESTAMP"+
                ");") == createUsersStmt);
            App.createTables(conn);
        } catch (SQLException e) {
            e.printStackTrace();
            assertTrue(false);
        }
    }

    @Mock PreparedStatement processUsersPS;
    @Test void appProcessUsers() {
        try{
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +users *"+
                "\\( *user_id *\\) *"+
                "VALUES *"+
                "\\( *\\? *\\) *;? *"
            ))).thenReturn(processUsersPS);
            App.processUsers(conn);
            verify(processUsersPS, times(394318)).setInt(eq(1), anyInt());
            verify(processUsersPS, times(394318)).addBatch();
            verify(processUsersPS).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
    }

    @Mock PreparedStatement processOrdersPS;
    @Test void appProcessOrders() {
        try{
            String columnsMatcher = "(order_id|created_at|website_session_id|user_id|primary_product_id|items_purchased|price_usd|cogs_usd)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +orders *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processOrdersPS);
            App.processOrders(conn);
            verify(processOrdersPS, times(32313)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processOrdersPS, times(32313*5)).setInt(anyInt(), anyInt());
            verify(processOrdersPS, times(32313*2)).setDouble(anyInt(), anyDouble());
            verify(processOrdersPS, times(32313)).addBatch();
            verify(processOrdersPS, atLeast(32)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
    }

    @Mock PreparedStatement processProductsPS;
    @Test void appProcessProducts() {
        try{
            String columnsMatcher = "(product_id|created_at|product_name)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +products *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processProductsPS);
            App.processProducts(conn);
            verify(processProductsPS, times(4)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processProductsPS, times(4)).setInt(anyInt(), anyInt());
            verify(processProductsPS, times(4)).setString(anyInt(), any(String.class));
            verify(processProductsPS, times(4)).addBatch();
            verify(processProductsPS, atLeast(1)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
    }

    @Mock PreparedStatement processOrderItemsPS;
    @Test void appProcessOrderItems() {
        try{
            String columnsMatcher = "(order_item_id|order_id|product_id|is_primary_item|price_usd|cogs_usd|created_at)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +order_items *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processOrderItemsPS);
            App.processOrderItems(conn);
            verify(processOrderItemsPS, times(40025)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processOrderItemsPS, times(40025*4)).setInt(anyInt(), anyInt());
            verify(processOrderItemsPS, times(40025*2)).setDouble(anyInt(), anyDouble());
            verify(processOrderItemsPS, times(40025)).addBatch();
            verify(processOrderItemsPS, atLeast(2)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
        
    }

    @Mock PreparedStatement processOrderItemRefundsPS;
    @Test void appProcessOrderItemRefunds() {
        try{
            String columnsMatcher = "(order_item_refund_id|order_item_id|order_id|refund_amount_usd|created_at)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +order_item_refunds *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processOrderItemRefundsPS);
            App.processOrderItemRefunds(conn);
            verify(processOrderItemRefundsPS, times(1731)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processOrderItemRefundsPS, times(1731*3)).setInt(anyInt(), anyInt());
            verify(processOrderItemRefundsPS, times(1731)).setDouble(anyInt(), anyDouble());
            verify(processOrderItemRefundsPS, times(1731)).addBatch();
            verify(processOrderItemRefundsPS, atLeast(2)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
    }

    @Mock PreparedStatement processWebsiteSessionsPS;
    @Test void appProcessWebsiteSessions() {
        try{
            String columnsMatcher = "(website_session_id|user_id|is_repeat_session|utm_source|utm_campaign|utm_content|device_type|http_referer|created_at)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +website_sessions *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processWebsiteSessionsPS);
            App.processWebsiteSessions(conn);
            verify(processWebsiteSessionsPS, times(472871)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processWebsiteSessionsPS, times(472871*3)).setInt(anyInt(), anyInt());
            verify(processWebsiteSessionsPS, times(472871*5)).setString(anyInt(), any(String.class));
            verify(processWebsiteSessionsPS, times(472871)).addBatch();
            verify(processWebsiteSessionsPS, atLeast(472)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
    }
    
    @Mock PreparedStatement processWebsitePageviewsPS;
    @Test void appProcessWebsitePageviews() {
        try{
            String columnsMatcher = "(website_pageview_id|website_session_id|pageview_url|created_at)";
            when(conn.prepareStatement(matches(
                " *INSERT +INTO +website_pageviews *"+
                "\\( *"+
                columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *, *"+columnsMatcher+
                " *\\) *"+
                "VALUES *"+
                "\\( *\\? *, *\\? *, *\\? *, *\\? *\\) *;? *"
            ))).thenReturn(processWebsitePageviewsPS);
            App.processWebsitePageviews(conn);
            verify(processWebsitePageviewsPS, times(1188124)).setTimestamp(anyInt(), any(Timestamp.class));
            verify(processWebsitePageviewsPS, times(1188124*2)).setInt(anyInt(), anyInt());
            verify(processWebsitePageviewsPS, times(1188124)).setString(anyInt(), any(String.class));
            verify(processWebsitePageviewsPS, times(1188124)).addBatch();
            verify(processWebsitePageviewsPS, atLeast(1188)).executeBatch();
        } catch(SQLException e){
            e.printStackTrace();
            assertTrue(false);
        }
        
    }
}
