/*
 * This source file was generated by the Gradle 'init' task
 */
package rooms.rest.service;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.naming.NamingException;
import javax.sql.DataSource;

import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import java.sql.ResultSet;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;


@Path("friends")
public class Friends {

    @Path("{sendingUID/{receivingUID}/{token}")
    public int sendFriendRequest (
        @PathParam("sendingUID") int sendingUID,
        @PathParam("receivingUID") int receivingUID,
        @PathParam("token") String token
    ){
        try {
        Context ctx = new InitialContext();
        DataSource ds = (DataSource)ctx.lookup("java:/comp/env/jdbc/");
        try {
            Connection conn = ds.getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT id FROM users WHERE token=?");
        {
            validateUserStmt.setString(1, token);
            ResultSet rs = validateUserStmt.executeQuery();
            if (!rs.next())
                rs.close();
                return 1;
            }
            int tokenUserID = rs.getInt(1);
            rs.close();
            if (tokenUserID != sendingUID)
                return 2;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } 
    catch (NamingException e) {
            System.out.println(e.getMessage());
    }
}
    }}
    // TODO Put this where it belongs
    PreparedStatement validateUserTmt = conn.prepareStatement("INSERT INTO friends (sendingUserID, receivingUserID) " + "VALUES (?, ?, ?);");
    insertRequestStmt.setInt(1, sendingUDI);
    insertRequestStmt.setInt(2, receivingUID);
    int inserted = insertRequestStmt.execcuteUpdate();
    return inserted == 1 ? 0 : 4;