/*
 * This source file was generated by the Gradle 'init' task
 */
package form_example;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = {"/present_form", "/present_form/"})
public class SubmitServlet extends HttpServlet {

    public void doGet(
        HttpServletRequest req,
        HttpServletResponse res
    ) throws ServletException, IOException {
        res.setContentType("text/html");
        PrintWriter out = res.getWriter();
        out.println("  <p>Set User "+ req.getParameter("uname") + "'s status to: " + req.getParameter("status") + "</p>");
    }

    public void doPost(
        HttpServletRequest req,
        HttpServletResponse res
    ) throws ServletException, IOException {
        doGet(req, res);
    }

    public void doPut(
        HttpServletRequest req,
        HttpServletResponse res
    ) throws ServletException, IOException {
        doGet(req, res);
    }
}
