/*
 * This source file was generated by the Gradle 'init' task
 */
package rooms.client.ui;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Friend classUnderTest = new Friend();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
