/*
 * This source file was generated by the Gradle 'init' task
 */
package pkm_data_installer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void canReadReleasesYaml() {
        
    }
}
