/*
 * This source file was generated by the Gradle 'init' task
 */
package rooms.client.ui;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Inject;

import java.sql.SQLException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import java.sql.Connection;

import jakarta.inject.Named;
import jakarta.ws.rs.client.ClientBuilder;

public class Friend {
    @Inject private userLoginBean login;
    private String message;
    
    @PostConstruct
    public void postConstruct() {
        try {
            Context ctx = new InitialContext();
            DataSource ds = (DataSource)ctx.lookup("java:/comp/env/jdbc/Assignment2");
            this.conn = ds.getConnection();
        } catch (NamingException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    @PreDestroy
    public void preDestroy() {

    }

    public void sendFriendRequest() {
        int sendingUID = 0;
        int receivingUID = 0;
        Client client = ClientBuilder.newClient();
        String name = client.target("http://localhost:8080/rooms-service/friends"
        .request(MediaType.TEXT_PLAIN)
        .get(String.class));
    }
}
