/*
 * This source file was generated by the Gradle 'init' task
 */
package servlet_example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloServletTest {
    @Test void appHasAGreeting() {
        HelloServlet classUnderTest = new HelloServlet();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
